name: tantawy
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: ^3.8.1

dependencies:
  sentry_flutter: ^9.8.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.3.2
  dio: ^5.9.0
  dio_smart_retry: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.2
  geolocator: ^13.0.2
  intl: ^0.19.0
  logger: ^2.5.0
  curved_navigation_bar: ^1.0.6
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2
  printing: ^5.13.4
  pdf: ^3.11.1
  shared_preferences: ^2.3.3
  shorebird_code_push: ^2.0.5
  
dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/fail.png
    - assets/images/invoice.png
    - assets/images/logo.png
    - assets/images/map.png
    - assets/images/order.png
    - assets/images/receipt.png
    - assets/images/bg.png
    - assets/images/bg-light.png
    - assets/images/transactions/new-invoice.png
    - assets/images/transactions/new-return-invoice.png
    - assets/images/transactions/new-receipt.png
    - assets/images/transactions/new-negative-visit.png
    - shorebird.yaml

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: casatek
